### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by lschmierer** [BoltzExchange/boltz-lnd#46]
I am running my LND node in a Kubernetes cluster.
Docker images for the Boltz LND client would be great!

Would a PR be accepted?

**Comment by lschmierer** [comment]
Would be great if Docker Images could be published for new releases! :)

**Comment by michael1011** [comment]
Just released a new version v1.2.6 with 2 bug fixes and pushed a Docker image for it: https://hub.docker.com/r/boltz/boltz-lnd/tags?page=1&ordering=last_updated

Do you also need an ARM build?

**Comment by lschmierer** [comment]
x86 is fine for me
Thank you very much!
