### ISSUE TITLE
Could not finalize refund transaction: could not broadcast transaction: min relay fee not met, 0 < 162

### ISSUE THREAD

**Issue by lschmierer** [BoltzExchange/boltz-lnd#49]
#48 was refunded after timeout.
I tried another Channel Creation which failed, too.

However, this time I get
```
INFO : 2021/07/19 14:37:46 Using fee of 0 sat/vbyte for refund transaction
INFO : 2021/07/19 14:37:46 Constructed refund transaction: 80ec7a7c08e3a2803cf9c92d434aec02b548300ec6d02def0c2cd750623f5ca6
ERROR: 2021/07/19 14:37:46 Could not finalize refund transaction: could not broadcast transaction: min relay fee not met, 0 < 162
```

**Comment by rkfg** [comment]
Same happened to me just now. I quickly worked around it with this:
```diff
diff --git a/nursery/reverse.go b/nursery/reverse.go
index 802d4ef..604a401 100644
--- a/nursery/reverse.go
+++ b/nursery/reverse.go
@@ -158,6 +159,9 @@ func (nursery *Nursery) handleReverseSwapStatus(reverseSwap *database.ReverseSwa
 			logger.Error("Could not get LND fee estimation: " + err.Error())
 			return
 		}
+		if feeSatPerVbyte < 1 {
+			feeSatPerVbyte = 1
+		}
 
 		logger.Info("Using fee of " + strconv.FormatInt(feeSatPerVbyte, 10) + " sat/vbyte for claim transaction")
 
```
But a proper investigation needed of course. With this patch your only risk is that the transaction might get stuck but you can recover it easily with CPFP.

**Comment by michael1011** [comment]
> Same happened to me just now. I quickly worked around it with this:

This patch should get the transaction trough.

> But a proper investigation needed of course

I think I already know what's wrong. What LND version are you guys using @rkfg @lschmierer?

**Comment by rkfg** [comment]
Compiled from master a few days ago, `lncli version 0.13.99-beta commit=v0.13.0-beta-113-g583dee99`

**Comment by lschmierer** [comment]
Compiled from master as well `v0.13.0-beta-131-gc4221c3c`

**Comment by lschmierer** [comment]
@michael1011 what was the motivation to get floor to 2 sats instead of 1 sat?

Also https://github.com/lightningnetwork/lnd/pull/5483 is probably related

**Comment by michael1011** [comment]
> @michael1011 what was the motivation to get floor to 2 sats instead of 1 sat?

Sorry for the late reply. The reason is that the onchain HTLCs are somewhat time critical and in my experience using a 2 sat/vbyte fee is more reliable when lnd suggests 1 sat/vbyte. I have had quite a few transactions stuck at 1 sat/vbyte in the past.
